name: 'Failure Slack message'
description: 'Shared action to send a Slack message if the process fails'
inputs:
  failure_message:
    description: 'Message to send'
    required: true
  slack_bot_token:
    description: 'Slack token to use'
    required: true
  channel_id:
    description: 'Slack channel to send to'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Send Slack error message
      uses: slackapi/slack-github-action@03ea5433c137af7c0495bc0cad1af10403fc800c # v3.0.2
      with:
        method: chat.postMessage
        token: ${{ inputs.slack_bot_token }}
        payload: |
          channel: ${{ inputs.channel_id }}
          text: "*${{ inputs.failure_message }}*"
          blocks:
            - type: section
              text:
                type: mrkdwn
                text: "⚠️ ${{ inputs.failure_message }}"
            - type: section
              fields:
                - type: mrkdwn
                  text: "*Please check the workflow results:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>"
            - type: section
              text:
                type: mrkdwn
                text: "_(generated by <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>)_"
    - name: Mark run as failed
      shell: bash
      run: |
        echo "::error::Update step failed; marking job as failed after sending Slack notification"
        exit 1
